name: Deploy New Bot

# Controls when the action will run.
on:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
env:
    REPO_NAME: ${{ github.event.repository.name }}
    TF_WORKING_DIR: ./terraform/test-bots
jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/test-bots
    steps:
    - uses: hashicorp/setup-terraform@v2
    - uses: actions/checkout@v2
      with:
        terraform_version: 1.1.9
        terraform_wrapper: false
        
    - name: Terraform init
      id: init
      run: terraform init
      env:
        GIT_SSH_COMMAND: "echo '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa && ssh-keyscan github.com > known_hosts && chmod 600 id_rsa known_hosts && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"

    - name: Terraform plan
      id: plan
      run: terraform plan
        
    - name: Terraform Output
      id: output
      run: terraform output -raw main_ip
    env:
      MAIN_IP: terraform output -raw main_ip

  install-requirements:
    needs: apply-terraform
    runs-on: ubuntu-latest
    steps:
    - name: installing requirements for ${{ env.REPO_NAME }} bot
      uses: fifsky/ssh-action@master
      with:
        command: |
          echo '###### Installing Git #######'
          sudo apt-get install git -y

          echo '###### Installing pip ######'
          sudo apt-get install python3-pip -y

          echo '###### Installing Discord Ext Menus ######'
          pip install -U git+https://github.com/Rapptz/discord-ext-menus

          echo '###### Installing Ap Scheduler ######'
          pip install apscheduler

          echo '###### Installing Discord.py ######'
          pip install discord.py
        host: 192.248.157.214
        user: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy-via-sftp:
    needs: install-requirements
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: 192.248.157.214
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /root/${{ env.REPO_NAME }}/

          # sftp args
          args: '-o ConnectTimeout=5'

  add-bot-token:
      needs: deploy-via-sftp
      runs-on: ubuntu-latest
      timeout-minutes: 2
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      steps:
      - name: executing remote ssh commands using ssh key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd baby-yoda/lib/bot
            touch token.0
            export ${{ env.BOT_TOKEN }}
            echo ${{ env.BOT_TOKEN }} > token.0
            echo $?
          host: 192.248.157.214
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  create-systemctl-service:
#    env:
#      REPO_NAME = ${{ env.REPO_NAME }}
    needs: add-bot-token
    runs-on: ubuntu-latest
    steps:
    - name: creating systemctl service
      uses: fifsky/ssh-action@master
      with:
        command: |
          export ${{ env.REPO_NAME }}
          echo "[Unit]
          Description=Baby Yoda Discord Bot
          After=multi-user.target

          [Service]
          Type=simple
          ExecStart=/root/${{ env.REPO_NAME }}/launcher.py
          User=root
          WorkingDirectory=/root/${{ env.REPO_NAME }}/
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target" >> /etc/systemd/system/${{ env.REPO_NAME }}.service

          chmod +x /root/${{ env.REPO_NAME }}/launcher.py
          sudo systemctl enable ${{ env.REPO_NAME }}.service
          sudo systemctl daemon-reload
          sudo systemctl start ${{ env.REPO_NAME }}.service
              
        host: 192.248.157.214
        user: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}

  create-systemctl-restart:
      needs: create-systemctl-service
      runs-on: ubuntu-latest
#      env:
#        REPO_NAME = ${{ env.REPO_NAME }}
      steps:
      - name: creating systemctl restart service
        uses: fifsky/ssh-action@master
        with:
          command: |
            export ${{ env.REPO_NAME }}
            echo "[Unit]
            Description=${{ env.REPO_NAME }} Discord Bot restart
            After=multi-user.target
            StartLimitInterval=10
            StartLimitBurst=5

            [Service]
            Type=oneshot
            ExecStart=/usr/bin/systemctl restart ${{ env.REPO_NAME }}.service

            [Install]
            WantedBy=multi-user.target" >> /etc/systemd/system/${{ env.REPO_NAME }}-watcher.service

            sudo systemctl enable ${{ env.REPO_NAME }}-watcher.service
            sudo systemctl start ${{ env.REPO_NAME }}-watcher.service

          host: 192.248.157.214
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}

  create-systemctl-watcher:
        needs: create-systemctl-restart
        runs-on: ubuntu-latest
  #      env:
  #          REPO_NAME = ${{ env.REPO_NAME }}
        steps:
        - name: creating systemctl watcher service
          uses: fifsky/ssh-action@master
          with:
            command: |
              echo "[Path]
              Unit=${{ env.REPO_NAME }}-watcher.service
              PathChanged=/root/${{ env.REPO_NAME }}

              [Install]
              WantedBy=multi-user.target" >> /etc/systemd/system/${{ env.REPO_NAME }}-watcher.path

              sudo systemctl enable ${{ env.REPO_NAME }}-watcher.path
              sudo systemctl start ${{ env.REPO_NAME }}-watcher.path

            host: 192.248.157.214
            user: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
