name: Deploy New Bot

# Controls when the action will run.
on:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
env:
    REPO_NAME: ${{ github.event.repository.name }}
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: 192.248.157.214
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /root/${{ env.REPO_NAME }}/

          # sftp args
          args: '-o ConnectTimeout=5'

  add-bot-token:
      needs: deploy-via-sftp
      runs-on: ubuntu-latest
      timeout-minutes: 2
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      steps:
      - name: executing remote ssh commands using ssh key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd baby-yoda/lib/bot
            touch token.0
            export ${{ env.BOT_TOKEN }}
            echo ${{ env.BOT_TOKEN }} > token.0
            echo $?
          host: 192.248.157.214
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  create-systemctl-service:
          needs: add-bot-token
          runs-on: ubuntu-latest
          steps:
          - name: creating systemctl service
            uses: fifsky/ssh-action@master
            with:
              command: systemctl.sh
              host: 192.248.157.214
              user: root
              key: ${{ secrets.SSH_PRIVATE_KEY }}
